// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCct6dCZ_QJPg5mYhArJipjm2DQdg5jpuM',
    appId: '1:999938755594:web:a9b402310e58f39deea3f3',
    messagingSenderId: '999938755594',
    projectId: 'sammi-46606',
    authDomain: 'sammi-46606.firebaseapp.com',
    databaseURL: 'https://sammi-46606-default-rtdb.firebaseio.com',
    storageBucket: 'sammi-46606.appspot.com',
    measurementId: 'G-GQE74D2DZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCc6c1zmGvamI1kXAEYYE7GWiPXvol-so',
    appId: '1:999938755594:android:794134a45afece9ceea3f3',
    messagingSenderId: '999938755594',
    projectId: 'sammi-46606',
    databaseURL: 'https://sammi-46606-default-rtdb.firebaseio.com',
    storageBucket: 'sammi-46606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBajzWtjbN5X22WW1yVF50wIkzEalvv2RI',
    appId: '1:999938755594:ios:e91b836d88d90f3aeea3f3',
    messagingSenderId: '999938755594',
    projectId: 'sammi-46606',
    databaseURL: 'https://sammi-46606-default-rtdb.firebaseio.com',
    storageBucket: 'sammi-46606.appspot.com',
    iosBundleId: 'boilerplate.template.riveprod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBajzWtjbN5X22WW1yVF50wIkzEalvv2RI',
    appId: '1:999938755594:ios:10710c8344343ea2eea3f3',
    messagingSenderId: '999938755594',
    projectId: 'sammi-46606',
    databaseURL: 'https://sammi-46606-default-rtdb.firebaseio.com',
    storageBucket: 'sammi-46606.appspot.com',
    iosBundleId: 'dev.feichtinger.template',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCct6dCZ_QJPg5mYhArJipjm2DQdg5jpuM',
    appId: '1:999938755594:web:1ec1691b78924396eea3f3',
    messagingSenderId: '999938755594',
    projectId: 'sammi-46606',
    authDomain: 'sammi-46606.firebaseapp.com',
    databaseURL: 'https://sammi-46606-default-rtdb.firebaseio.com',
    storageBucket: 'sammi-46606.appspot.com',
    measurementId: 'G-KN8WYV4S7L',
  );

}